# Generated by Django 2.2.10 on 2020-12-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantagesoption',
            name='option_slug',
        ),
        migrations.RemoveField(
            model_name='advantagesoption',
            name='option_title',
        ),
    ]
