# Generated by Django 2.2.10 on 2020-12-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201230_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='advantage',
        ),
        migrations.DeleteModel(
            name='AdvantagesOption',
        ),
        migrations.DeleteModel(
            name='AdvantagesOptionSet',
        ),
    ]
