# Generated by Django 2.2.10 on 2020-12-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201230_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='advantage1',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='advantage2',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
