# Generated by Django 2.2.10 on 2020-12-30 16:21

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201230_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('citation', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='advantage1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='advantage2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
