# Generated by Django 2.2.10 on 2020-12-31 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201230_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intro',
            name='citation',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='intro',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
