# Generated by Django 2.2.10 on 2021-01-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
